; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32 @ 7.0.1
board_build.esp-idf.sdkconfig_path = sdkconfig694
; board_build.esp-idf.sdkconfig_path = sdkconfigOG

; platform = espressif32 #esp-idf version v5.3.2
; board_build.esp-idf.sdkconfig_path = sdkconfig694pu
; board_build.esp-idf.sdkconfig_path = sdkconfig694OGpu 

board = esp32doit-devkit-v1
framework = espidf
monitor_speed = 921600
upload_port = /dev/tty.usbserial-0001
monitor_port = /dev/tty.usbserial-0001
monitor_filters = direct, esp32_exception_decoder
extra_scripts = pre:kill_frozen_monitor.py
build_flags = -Wno-missing-field-initializers